default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: rye run ruff check .
        language: system
        pass_filenames: false
      - id: black
        name: black
        entry: rye run black --check .
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: rye run mypy --explicit-package-bases .
        language: system
        pass_filenames: false
      - id: isort
        name: isort
        entry: rye run isort --check .
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: rye run pytest -s
        language: system
        pass_filenames: false
      # - id: interrogate
      #   name: interrogate
      #   entry: interrogate .
      #   language: system
      #   pass_filenames: false